### ISSUE TITLE
Port Housekeeping Tools

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/ui#1]
Need to port over housekeeping tools:

```[tasklist]
### Tasks
- [x] .eslintrc.json and .eslintignore https://github.com/freeCodeCamp/ui/pull/33
- [x] .prettierrc and .prettierignore https://github.com/freeCodeCamp/ui/pull/17
- [x] husky https://github.com/freeCodeCamp/ui/pull/33
- [x] .editorconfig https://github.com/freeCodeCamp/ui/pull/17
- [x] .npmrc the default behaviour seems fine at the moment.
- [ ] .nvmrc https://github.com/freeCodeCamp/ui/pull/62
- [x] renovate https://github.com/freeCodeCamp/ui/pull/39
```
